# Generated by Django 3.2.3 on 2021-05-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210526_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
